services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strategiclear-spring-boot-app
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:./proddb;DB_CLOSE_DELAY=-1
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa